print('hello world')
print('what is your name')
myName = input()
print('my name is ' + myName)
print('the charecters presented in your name is :')
print(len(myName))
print('what is your age')
myAge = input()
print('my age is '+ str(int(myAge) + 1) )  
